### PR TITLE
chore(attachments): create attachments component to alleviate duplicate code

### PR DESCRIPTION
**Pull request by Jekrimo**
### What this PR does 📖

- create attachments component to alleviate duplicate code

### Which issue(s) this PR fixes 🔨

- Resolve #
- No resolve # for this issue

### Special notes for reviewers 🗒️
For testing, attachments should look and function exactly how they already do. 

Also, this pr is dependent on the #652 pr going in first

### CODE REVIEW

**Review by lgmarchi — APPROVED** [review]

**Comment by phillsatellite** [comment]
Hey brotha! Just a small issue, after sending an attachment in chat the user cannot open said attachment and preview it. Seems to be happening just in chats if I go to Files page I can still open and preview files 

https://github.com/user-attachments/assets/01f59bf2-3f43-4dc3-81c1-ef63444e38d5

**Comment by Jekrimo** [comment]
Thank you and pretty sure I got it fixed @phillsatellite !

**Comment by phillsatellite** [comment]
So functionality is working a lot better! Theres just one issue that doesnt happen on dev, if your browser is not fullscreen and you open up the attachment half of the preview will render behind the sidebar
 
https://github.com/user-attachments/assets/315ca5a2-ca30-452b-bb42-0e2afe926cc4

**Comment by Jekrimo** [comment]
Hey @phillsatellite ! after a long battle with css and a boatload of merge issues  I decided to have a little work around and it should be good now!

**Review by stavares843 — APPROVED** [review]

**Review by phillsatellite — APPROVED** [review]

**Pull request merged**
