### PR TITLE
chore(wasm): updates wasm + group icon

### LINKED ISSUE #662: fix(Group): With warp update, need to adjust group settings on UplinkWeb
- Update uplink web with new group settings from Warp
- Update warp-wasm package to use on Uplink Web with new Group Settings feature

### LINKED ISSUE #771: Group settings - Change photo of group is not wired (not saved)
The option to change the photo in group settings does not save the changes. 

- The group owner is able to change the picture but if you are not the owner even if you are given permission you are not able to change the group photo

### LINKED ISSUE #773: Group settings - Changes to switch for allow anyone to change photo are not saved
Changes to the switch to allow anyone to change the group photo are not being saved.

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Updates wasm to 1.6.2
- Fixes permission issue with kicking users. A new permission to allow that was added
- Updated various wasm typings in warp integration
- Added group/chat icon (technically banner too but atm no way to change and/or display that)
- Wired up the possibility to change group icon

### Which issue(s) this PR fixes 🔨

- Resolve #662
- Resolve #771
- Resolve #773

### CODE REVIEW

**Comment by phillsatellite** [comment]
Having some weird issues. This pr broke all 3 of my accounts and Sara's as well. Incognito works fine but most of all the users we will have will not be using incognito browsers to use our app

Switch from dev to this branch (can be a brand new account or old account will still break)

Note that I have tried clearing my cache and restarting my browser over 20 times and no matter what I do I end up at this endless loading screen 

This error appears in console - 

(in promise) LinkError: WebAssembly.instantiate(): Import # 1 "wbg" "__wbg_friendrequest_new": function import requires a callable

This is Sara's account it was brand new, no friends, no chats, no nothing but still cannot load if we are on this branch 
image

My accounts
Screenshot 2024-11-20 at 3 28 48 PM

**Review by stavares843 — CHANGES_REQUESTED** [review]
also, that error if you click on it goes to line 194 on src/layouts/page+svelte

https://github.com/Satellite-im/UplinkWeb/blob/dev/src/routes/%2Blayout.svelte#L194

Captura de ecrã 2024-11-20, às 20 31 21


browser - chrome

not private

**Comment by Flemmli97** [comment]
i had that happen once... and now i cant reproduce it anymore. tried different browsers, refreshing multiple times etc. can you test again?

**Review by stavares843 — COMMENTED** [review]
its always reproducible here

**Comment by phillsatellite** [comment]
Replicated again this morning 

Screenshot 2024-11-21 at 11 52 41 AM

**Comment by phillsatellite** [comment]
So was able to test with Sara with the fix you gave us but I had some weird behavior that Sara wasnt able to replicate. If you cant replicate either its all good wont try to hold this up any longer just wanted to mention it

So with the group that I created everything works fine but when I go to the group that Sara created my entire app freezes up and I get the error that I posted below. If I refresh I can move around the app again until I go to the group Sara created then it breaks again. I created a group with another account and it also seemed to work fine but that was with another account on the same local network so maybe it could be something sometimes happening with users not over local net

https://github.com/user-attachments/assets/28153abd-4d66-4234-b796-8c64968cf553

Screenshot_2024-11-22_at_1 45 02_PM

**Comment by phillsatellite** [comment]
Noticed something while testing with Sara. 

When a user tries to kick themselves from the group nothing happens on their side and they remain in the group. 

I also still get a bug sometimes when whole app just freezes but it seems totally random 

Flow: 
-UserB kicks themselves 
-On UserB side nothing changes and they appear as if they are in the group still 
-On UserA side it appears that UserB is no longer in the group 
-After UserB kicks themselves but groupchat remains on their side any messages sent in the groupchat userB will not receive. 


There doesn't seem to be any error in chat when UserB kicks themselves 

https://github.com/user-attachments/assets/57f6114a-10fd-4fed-9751-12ae55e4071f

**Comment by Flemmli97** [comment]
> So was able to test with Sara with the fix you gave us but I had some weird behavior that Sara wasnt able to replicate. If you cant replicate either its all good wont try to hold this up any longer just wanted to mention it
> 
> So with the group that I created everything works fine but when I go to the group that Sara created my entire app freezes up and I get the error that I posted below. If I refresh I can move around the app again until I go to the group Sara created then it breaks again. I created a group with another account and it also seemed to work fine but that was with another account on the same local network so maybe it could be something sometimes happening with users not over local net
> 
>  Screen_Recording_2024-11-22_at_1.44.38_PM.mov 
> 
> Screenshot_2024-11-22_at_1 45 02_PM

thats strange. as the data there shouldnt be undefined... i could for now add a check for that though

**Comment by Flemmli97** [comment]
> Noticed something while testing with Sara.
> 
> When a user tries to kick themselves from the group nothing happens on their side and they remain in the group.
> 
> I also still get a bug sometimes when whole app just freezes but it seems totally random
> 
> Flow: -UserB kicks themselves -On UserB side nothing changes and they appear as if they are in the group still -On UserA side it appears that UserB is no longer in the group -After UserB kicks themselves but groupchat remains on their side any messages sent in the groupchat userB will not receive.
> 
> There doesn't seem to be any error in chat when UserB kicks themselves
> 
>  Screen.Recording.2024-11-25.at.10.02.48.AM.mov

do we even want someone to kick themselves?

**Comment by phillsatellite** [comment]
> > Noticed something while testing with Sara.
> > When a user tries to kick themselves from the group nothing happens on their side and they remain in the group.
> > I also still get a bug sometimes when whole app just freezes but it seems totally random
> > Flow: -UserB kicks themselves -On UserB side nothing changes and they appear as if they are in the group still -On UserA side it appears that UserB is no longer in the group -After UserB kicks themselves but groupchat remains on their side any messages sent in the groupchat userB will not receive.
> > There doesn't seem to be any error in chat when UserB kicks themselves
> > Screen.Recording.2024-11-25.at.10.02.48.AM.mov
> 
> do we even want someone to kick themselves?

I mean right now thats the only way for a user to leave a group they dont wanna be in

**Comment by Flemmli97** [comment]
> > > Noticed something while testing with Sara.
> > > When a user tries to kick themselves from the group nothing happens on their side and they remain in the group.
> > > I also still get a bug sometimes when whole app just freezes but it seems totally random
> > > Flow: -UserB kicks themselves -On UserB side nothing changes and they appear as if they are in the group still -On UserA side it appears that UserB is no longer in the group -After UserB kicks themselves but groupchat remains on their side any messages sent in the groupchat userB will not receive.
> > > There doesn't seem to be any error in chat when UserB kicks themselves
> > > Screen.Recording.2024-11-25.at.10.02.48.AM.mov
> > 
> > 
> > do we even want someone to kick themselves?
> 
> I mean right now thats the only way for a user to leave a group they dont wanna be in

ok. it seems like that we simply dont receive the conversation deleted event when kicking ourselfs. this is most likely a warp problem and thus i would say we make a ticket for it and handle it in another pr to not hold this up anymore

**Comment by phillsatellite** [comment]
Hey Kevin! Gonna approve this today there are just a few things Im gonna create tickets for that I wanted to mention here 

-Chat remains when user kicks themselves (maybe for the ticket we can instead make it like "User should have a way to leave the group")
-Non-Creator cannot change group photo 
-Users cannot clear photo once selected

Thanks for all the work on this pr!

**Review by phillsatellite — APPROVED** [review]

**Review by stavares843 — APPROVED** [review]

**Review by InfamousVague — APPROVED** [review]
LGTM, ChatIcon might be confusing for the name but I don't think it's worth changing anything over

**Review by luisecm — APPROVED** [review]

**Pull request merged**
