### PR TITLE
fix(CallPopUp): Enable call pop up when user is out of active call chat

### LINKED ISSUE #854: bug(Calling): PopOut viewer is missing
**Issue:**
It looks like somewhere along the way we lost the popOut feature we had within calling. This ticket is to add that feature back in

**Screen recording:**

https://github.com/user-attachments/assets/8cec3411-deef-4312-a52b-e29853cad6bb

### PR DESCRIPTION
**Pull request by lgmarchi**
### What this PR does 📖

This pull request includes significant updates to the `VideoPreview` component in the calling module. The changes involve enhancing the video preview functionality, improving the user interface, and fixing the visibility toggle for the call screen.

Enhancements to `VideoPreview` functionality:

* [`src/lib/components/calling/VideoPreview.svelte`](diffhunk://#diff-b7aa19d0d1775d421148b8fab91e7c6405434126eaa9815546957d82587d5eedL2-R105): Replaced the `show` variable with `showVideoPreview` to control the visibility of the video preview, and added logic to sort and filter users based on their audio status.
* [`src/lib/components/calling/VideoPreview.svelte`](diffhunk://#diff-b7aa19d0d1775d421148b8fab91e7c6405434126eaa9815546957d82587d5eedL2-R105): Implemented a new `attachStream` function to handle the attachment of video streams to video elements.

User interface improvements:

* [`src/lib/components/calling/VideoPreview.svelte`](diffhunk://#diff-b7aa19d0d1775d421148b8fab91e7c6405434126eaa9815546957d82587d5eedL110-R193): Updated the video preview container to use a grid layout for displaying multiple video streams, and added styles to improve the appearance and layout of video elements. [[1]](diffhunk://#diff-b7aa19d0d1775d421148b8fab91e7c6405434126eaa9815546957d82587d5eedL110-R193) [[2]](diffhunk://#diff-b7aa19d0d1775d421148b8fab91e7c6405434126eaa9815546957d82587d5eedL167-R309)

Visibility toggle fix:

* [`src/lib/media/Voice.ts`](diffhunk://#diff-a75896c18790a15b7e0ae422d555a80c3e09067296e47a5dcc6891ab3385dfb4L737): Moved the `callScreenVisible.set(false)` statement to ensure the call screen visibility is correctly toggled when leaving a call. [[1]](diffhunk://#diff-a75896c18790a15b7e0ae422d555a80c3e09067296e47a5dcc6891ab3385dfb4L737) [[2]](diffhunk://#diff-a75896c18790a15b7e0ae422d555a80c3e09067296e47a5dcc6891ab3385dfb4R761)

Re-enabling the `VideoPreview` component:

* [`src/routes/+layout.svelte`](diffhunk://#diff-cc69d6a97e4f62578028d872b8d5032f2786fe1eaa65735429286b375234168dL293-R293): Re-enabled the `VideoPreview` component in the layout by removing the comment that was disabling it.

### Special notes for QAs 🧪

- It will just show 3 users in Video Preview, even if call has 10 users on it. But, if last user in call, start to speak, he will be changed to the first place in the list, and will appear on Video Preview. 

    <details><summary>Video</summary>
    <p>
    
    
    https://github.com/user-attachments/assets/c4e70ce1-2d9e-4fc5-8c5b-ab082baf3219
    
    
    
    </p>
    </details> 

- When user leave a call, should update video preview immediately. 

    <details><summary>Video</summary>
    <p>
    
    
    https://github.com/user-attachments/assets/1766cf51-644f-4371-9def-b596f3e3dfba
    
    
    </p>
    </details> 
    
 - It works with video enabled too.
 
     <details><summary>Image</summary>
    <p>
    
    
    image
    
    
    </p>
    </details> 

### Which issue(s) this PR fixes 🔨

-   Resolve #854

### CODE REVIEW

**Comment by lgmarchi** [comment]
@stavares843 and @phillsatellite I think it has a problem yet, when we test with user that didn't do the call.

**Comment by lgmarchi** [comment]
- Add feedback when waiting other users to join 
image

- Now showing quantity of users active in call 
image

**Review by stavares843 — CHANGES_REQUESTED** [review]
so i tested with @phillsatellite and both on group and also on 1:1 and i had the following bug

https://github.com/user-attachments/assets/6d15a1e5-5799-4951-afc7-efd6b5993a11



then both @phillsatellite and i had the following bug


https://github.com/user-attachments/assets/79c070c1-40f8-44a4-99dd-c5bb06679d9a



also no image when i activate video but worked for @phillsatellite - works on dev 

image


browser - chrome

**Comment by lgmarchi** [comment]
> so i tested with @phillsatellite and both on group and also on 1:1 and i had the following bug
> 
>  Gravacao.do.ecra.2024-11-19.as.22.15.52.mov 
> then both @phillsatellite and i had the following bug
> 
>  290390209.mov 
> also no image when i activate video but worked for @phillsatellite - works on dev
> 
> image
> 
> browser - chrome

Very interesting, I will do more tests and try to improve this code.

**Comment by lgmarchi** [comment]
> so i tested with @phillsatellite and both on group and also on 1:1 and i had the following bug
> 
>  Gravacao.do.ecra.2024-11-19.as.22.15.52.mov 
> then both @phillsatellite and i had the following bug
> 
>  290390209.mov 
> also no image when i activate video but worked for @phillsatellite - works on dev
> 
> image
> 
> browser - chrome

I did a commit for it.

**Review by phillsatellite — APPROVED** [review]

**Review by stavares843 — APPROVED** [review]

**Review by ashneverdawn — APPROVED** [review]

**Pull request merged**
