### PR TITLE
fix(conversations): fix typing issue of list_conversations() with warp-wasm 1.3.0

### PR DESCRIPTION
**Pull request by ashneverdawn**
### What this PR does 📖

- Updates warp-wasm to 1.3.0
- Updates `list_conversations()` for warp-wasm 1.3.0 (fix typing issue)

### CODE REVIEW

**Review by tooshel — COMMENTED** [review]
Why is the () back on the id? To me it made sense to just be id and if you wanted to call a getter, you would call "getid()" or something like that. Is that convention old school?

**Comment by ashneverdawn** [comment]
> Why is the () back on the id? To me it made sense to just be id and if you wanted to call a getter, you would call "getid()" or something like that. Is that convention old school?

actually the underlying struct in warp has `id()` getter function. The naming of the getter functions is consistent with other existing data structures in the warp repo (no `get_` prefix). The reason why we needed to remove the paren before, is because serge_wasmbindgen was discarding the functions and exposing the private properties, so we had to use `id`. Now that we've worked around using serge_wasmbindgen for this function in warp, we can call `id()` the expected way, and typescript isn't confused about the type anymore.

**Review by tooshel — APPROVED** [review]
Well, the squiggly line is gone in the editor AND it works so it's a win overall!

**Comment by Flemmli97** [comment]
i fixed this already in #272 so not sure what we should prefer now

**Comment by ashneverdawn** [comment]
> i fixed this already in #272 so not sure what we should prefer now

oh nice! go ahead and merge yours then. I'll close this one. Thanks!

**Pull request closed without merging**
