### PR TITLE
feat(App): Improve sidebar animation

### PR DESCRIPTION
**Pull request by lgmarchi**
### What this PR does 📖

- Add slide animation on sidebar for web and mobile

<details><summary>Video Exemple on Web</summary>
<p>

https://github.com/user-attachments/assets/86ffc9ad-3a07-4643-a0bb-e65f7130c438

</p>
</details> 

### Which issue(s) this PR fixes 🔨

-   Resolve #

### CODE REVIEW

**Comment by luisecm** [comment]
@lgmarchi Hello Lucas, on this PR I found the same bug happening in #926 

1. Open in mobile view
2. Click on create group chat
3. Create group modal is not visible until  you swipe to the right (like in the video from the example):
https://github.com/user-attachments/assets/79109dba-a018-4257-8676-71826c7100e1

**Comment by lgmarchi** [comment]
> @lgmarchi Hello Lucas, on this PR I found the same bug happening in #926
> 
> 1. Open in mobile view
> 2. Click on create group chat
> 3. Create group modal is not visible until  you swipe to the right (like in the video from the example):
>    https://github.com/user-attachments/assets/79109dba-a018-4257-8676-71826c7100e1

I would say that, in other PR when you saw error, probably is related with this one. and I know already what it is.

**Comment by lgmarchi** [comment]
> @lgmarchi Hello Lucas, on this PR I found the same bug happening in #926
> 
> 1. Open in mobile view
> 2. Click on create group chat
> 3. Create group modal is not visible until  you swipe to the right (like in the video from the example):
>    https://github.com/user-attachments/assets/79109dba-a018-4257-8676-71826c7100e1

Fixed.

**Comment by phillsatellite** [comment]
Hey Lucas so on mobile this is working pretty good for me but on web browser the navBar seems to be missing. If you close the sidebar the navBar will appear but only Files Chats and Friends will appear

Screenshot 2024-12-09 at 6 35 55 PM
Screenshot 2024-12-09 at 6 36 14 PM

**Comment by lgmarchi** [comment]
> Hey Lucas so on mobile this is working pretty good for me but on web browser the navBar seems to be missing. If you close the sidebar the navBar will appear but only Files Chats and Friends will appear
> 
> Screenshot 2024-12-09 at 6 35 55 PM Screenshot 2024-12-09 at 6 36 14 PM

@phillsatellite For me is working pretty good. I realized, for some reason, your app is cutting in the end. 

https://github.com/user-attachments/assets/b611e158-62f3-457a-bb66-07822ac551a4


Did you test in other browser?

**Comment by phillsatellite** [comment]
> > Hey Lucas so on mobile this is working pretty good for me but on web browser the navBar seems to be missing. If you close the sidebar the navBar will appear but only Files Chats and Friends will appear
> > Screenshot 2024-12-09 at 6 35 55 PM Screenshot 2024-12-09 at 6 36 14 PM
> 
> @phillsatellite For me is working pretty good. I realized, for some reason, your app is cutting in the end.
> 
>  Screen.Recording.2024-12-10.at.09.37.02.mov 
> Did you test in other browser?

Ive tested this on both old and new accounts, replicated on brave and chrome, made sure to do npm i before compiling. I can replicate this each time I switch to this branch. Im having @stavares843 & @luisecm  try to verify for me as well. This bug also happens wether the browser is in fullscreen or not

**Comment by phillsatellite** [comment]
Tested again, new account, brand new build still getting the bug 

https://github.com/user-attachments/assets/78274716-cba4-4a5d-b23d-217d65b5bf95

**Comment by luisecm** [comment]
@lgmarchi Hey Lucas, I am able to see the same bugs reported by Phil on my end too:

- Regular desktop browser resolution fails to show the navbar
- Ipad resolution on desktop browser fails to show the navbar
- Mobile resolutions (iphone 12, pixel 4) on desktop browser show correctly the navbar

Also, when hidiing the sidebar, the navbar appears at the left is missing settings button


https://github.com/user-attachments/assets/138e2773-62ba-4bd9-8583-88a759811528

**Comment by lgmarchi** [comment]
Problem was css height, I changed the property, let's see if it will solve the problem.

**Review by phillsatellite — APPROVED** [review]

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
