### PR TITLE
feat(chat): impl file sharing chat

### LINKED ISSUE #567: task(Chat): Wire up Share Files
**Issue:**
When you send a message in chat there is a Share button that doesnt seem to be hooked up yet. Luis and I are thinking this is for sharing said file with other friends on Uplink. If so then when clicked a list of friends should pop up and user should be able to select multiple friends from that list and send file to 

**Screenshot:**
image

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Implements file sharing button for files in chat
  - Adds back the share button for file type attachments (image e.g. dont have this)
  - Clicking on it opens a share modal where you can select multiple chats
  - Sending it will send the file to all selected chats

### Which issue(s) this PR fixes 🔨

- Resolve #567

### CODE REVIEW

**Review by InfamousVague — APPROVED** [review]

**Comment by phillsatellite** [comment]
@Flemmli97 Im getting some weird behavior when trying to test this. Sometimes the attachment will send through but most times it will not. Ive tried this on Safari/Chrome/Brave Ive done all new accounts, Ive also tried refreshing the accounts if need be 

When the attachment doesnt send it just sends a blank bubble in the chat and this error appears in console 

```Logger.ts:46 [ERROR] (12:44:45 PM):  Error uploading file No attachments provided for message```

https://github.com/user-attachments/assets/c8a87428-ad93-4fd6-b91f-469fa18288de

**Comment by phillsatellite** [comment]
@Flemmli97 Retested with Sara and we both had a lot of issues 

When you try to send a file it doesnt seem to be sending correctly. User will get a notification like they got a new message but when they go to chat no new message appears only the banner that says "new message"

After the sender sends a file it kinda breaks the entire app. User cannot use the nav bar to navigate anymore, if they refresh chat either endlessly loads or just loads a black screen. 

It was throwing these errors in logs for both Sara and I 
Screenshot 2024-10-17 at 12 14 52 PM

https://github.com/user-attachments/assets/92a0f875-8875-430b-99cd-96c719ecbc48

**Comment by luisecm** [comment]
@Flemmli97 Automation test caught the following bug:

1. Go to chat
2. Select upload file and pickup any file
3. Then select upload file and pickup another file
4. Chatbar preview before sending message includes two attachment previews
5. Click on send message
6. Message with the two attachments is not sent and chatbar preview disappears

**Comment by Flemmli97** [comment]
> @Flemmli97 Retested with Sara and we both had a lot of issues
> 
> When you try to send a file it doesnt seem to be sending correctly. User will get a notification like they got a new message but when they go to chat no new message appears only the banner that says "new message"
> 
> After the sender sends a file it kinda breaks the entire app. User cannot use the nav bar to navigate anymore, if they refresh chat either endlessly loads or just loads a black screen.
> 
> It was throwing these errors in logs for both Sara and I Screenshot 2024-10-17 at 12 14 52 PM
> 
>  Screen.Recording.2024-10-17.at.12.08.29.PM.mov

fixed. was a bug from merging

**Review by phillsatellite — APPROVED** [review]

**Pull request merged**
