### PR TITLE
feat(call): Call UI rework

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Redo the call ui:
  - Users in call are ordered dynamically on max 2 rows.
  - If there are still more users in the call pages are added with buttons on the top bar that allows switching between
  - Put some restraint on the whole ui (e.g. max 60% of current height) so it does not cover the whole page
  - Reduce user icon size as currently it is quite large

### CODE REVIEW

**Comment by luisecm** [comment]
@Flemmli97 The videocalls E2E test is failing because there is a minor change css in background color of the enable/disable button after enabling camera. Since this is minor and does not affect functonality, I went ahead and added a PR updating the test with the new CSS value and its passing against your branch, so we are good with this small change: 

image


https://github.com/Satellite-im/automated-tests-web/pull/187

**Comment by phillsatellite** [comment]
Hey Flem! When we go into fullscreen the video feed is almost the same size as my screen and renders off the sides. Is this intended? 

image

**Comment by Flemmli97** [comment]
> Hey Flem! When we go into fullscreen the video feed is almost the same size as my screen and renders off the sides. Is this intended?
> 
> image

~~is that screenshot your whole screen?~~

**Review by phillsatellite — APPROVED** [review]

**Comment by Flemmli97** [comment]
i added an update that addresses following:
if a user is currently not on the current page then their media will not play

changed:
all media now on the page but non relevants are hidden

**Comment by phillsatellite** [comment]
With the latest changes there is a new bug. Now when the user is in a call and they go to any other page they can no longer hear the call. And when they go back all the audio they missed starts coming in and echos. We should have it so the user can hear the audio from the call no matter what page they are on 

https://github.com/user-attachments/assets/045d0142-2b20-4a13-b694-2c474a5ad403

**Comment by Flemmli97** [comment]
> With the latest changes there is a new bug. Now when the user is in a call and they go to any other page they can no longer hear the call. And when they go back all the audio they missed starts coming in and echos. We should have it so the user can hear the audio from the call no matter what page they are on
> 
>  Screen.Recording.2024-10-29.at.12.00.19.PM.mov

the "page" i refer to is a page in chat. not e.g. chat/friends page
you stay in the chat and if there are more people some buttons will appear allowing you to switch between users.
i think atm you need to be in the chat to hear calls properly, correct me if im wrong, even without the recent change

with the screenshot you sent you should be able test it with 3 users

**Review by ashneverdawn — APPROVED** [review]

**Pull request merged**
