### PR TITLE
fix(friend-request): update friendRequestDid regex and adjust request string handling

### LINKED ISSUE #858: refactor(DID): Remove did:key: from DID to share with others
Remove did:key: from DID to share with others

### PR DESCRIPTION
**Pull request by lgmarchi**
### What this PR does 📖

This pull request includes several changes to improve the handling of DID keys and user#858 erences in the application. The most important changes include modifying the friend request DID validation, updating the friend request string format, and ensuring user keys are copied without the "did:key:" prefix.

Changes to DID key handling and user references:

* [`src/lib/utils/CommonInputRules.ts`](diffhunk://#diff-3d012ec945a2a1c4aee1f8fcbd451fa8b275ee442b26ae9a596b4098a745a43aL6-R6): Updated the `friendRequestDid` regex pattern to remove the "did:key:" prefix requirement.
* [`src/routes/friends/+page.svelte`](diffhunk://#diff-8ce6fbdb2e24d80840557fce3b7c2daaa246fd6cf83e3e9ad87075f2f30a4c1dL72-R74): Modified the friend request string to include the "did:key:" prefix before sending the request.
* [`src/routes/friends/+page.svelte`](diffhunk://#diff-8ce6fbdb2e24d80840557fce3b7c2daaa246fd6cf83e3e9ad87075f2f30a4c1dL157-R159): Updated the clipboard copy function to remove the "did:key:" prefix from the user key.
* [`src/routes/settings/profile/+page.svelte`](diffhunk://#diff-3075e5e7f3f4c9f8c32deabd421e2e1c394b2a94cf56aa783e0a7c7aa021695cL239-R239): Updated the clipboard copy function to remove the "did:key:" prefix from the user reference key.

> [!NOTE]
>  https://github.com/user-attachments/assets/67b8d93a-5d86-4bae-8fdf-d1ee117b3916

### Which issue(s) this PR fixes 🔨

-   Resolve #858

### CODE REVIEW

**Review by stavares843 — COMMENTED** [review]
do you wanna hide the did from the groups list?


image

**Review by stavares843 — COMMENTED** [review]
and here as well

image

**Comment by phillsatellite** [comment]
@lgmarchi we noticed another bug when testing bro

If users remove each other and re-add them they wont be able to send messages or call unless they refresh webpage (I couldn't replicate these issues on the dev branch)

**Flow:**
User A removes User B 
User A adds User B back 
User A tries to send message to User B 
They get error in console 

User A removes User B 
User A adds User B back 
User A tries to call User B 
User B tries to answer and they get error 

Error when trying to send message 
image

https://github.com/user-attachments/assets/3cd191f7-e8d9-4819-967b-82f7eb87b743

Error when trying to accept a call 
image

**Comment by lgmarchi** [comment]
> @lgmarchi we noticed another bug when testing bro
> 
> If users remove each other and re-add them they wont be able to send messages or call unless they refresh webpage (I couldn't replicate these issues on the dev branch)
> 
> **Flow:** User A removes User B User A adds User B back User A tries to send message to User B They get error in console
> 
> User A removes User B User A adds User B back User A tries to call User B User B tries to answer and they get error
> 
> Error when trying to send message image
> 
>  Screen_Recording_2024-11-18_at_6.07.49_PM.mov 
> Error when trying to accept a call image

Weird thing, I didn't change code to happen it. I will do more tests.

**Comment by lgmarchi** [comment]
@phillsatellite I did a commit just to improve code, but nothing changed. 

I really didn't change anything about message or calls. 

And I did at least 5 tests here with flow you suggested, worked fine for me. 

<details><summary>Image Showing Test Result</summary>
<p>

image

</p>
</details> 


<details><summary>Video showing tests</summary>
<p>


https://github.com/user-attachments/assets/3b7b79a0-dafe-4a3d-ae2b-cb4c1a6e170c

</p>
</details>

**Comment by lgmarchi** [comment]
> do you wanna hide the did from the groups list?
> 
> image

I asked Kevin, he said to change to new key, so it was changed. 

image


image

**Review by phillsatellite — APPROVED** [review]

**Comment by phillsatellite** [comment]
@lgmarchi hey bro so Sara and I tried replicating the bug I reported above again today and I think yesterday I might've reported wrong. We tested unfriending and re adding and that worked fine each time. But then we tried blocking/unblocking and re adding and thats when the bug would appear user is not able to send any messages in chat. If you want I can try this flow with you so we can see whats going on with it 

So flow is 
UserA blocks UserB
UserA unblocks UserB 
UserB re-adds UserA as a friend 
Neither can send messages in chat 

This error floods console 
image

**Comment by lgmarchi** [comment]
> @lgmarchi hey bro so Sara and I tried replicating the bug I reported above again today and I think yesterday I might've reported wrong. We tested unfriending and re adding and that worked fine each time. But then we tried blocking/unblocking and re adding and thats when the bug would appear user is not able to send any messages in chat. If you want I can try this flow with you so we can see whats going on with it
> 
> So flow is UserA blocks UserB UserA unblocks UserB UserB re-adds UserA as a friend Neither can send messages in chat
> 
> This error floods console image

I think we can try together, I tested here and didn't have problem. 

I tried 3 times, no problem. 






<details><summary>Video showing tests</summary>
<p>

https://github.com/user-attachments/assets/beb6c1e3-4390-498b-b323-ae8f3de3b502


</p>
</details>

**Review by ashneverdawn — APPROVED** [review]

**Pull request merged**
