### PR TITLE
fix(files): File rework

### LINKED ISSUE #428: bug(Files): User can drag a folder into a file
**Issue:**
The user is able to drag a folder into a file. If they do this the folder will disappear 

 **Screen recording:**

https://github.com/user-attachments/assets/8d5e5446-9038-44fb-9d89-0ef3540f0d00

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Update files page stuff
  - Remove the whole folderstack thing and instead update the files directly from warp
  - Fix some store subscription things. e.g. not unsubscribing (change to `$:` syntax)
  - Fix drag drop into folder triggering for everyfile instead of just target file moving all files into the target folder
  - Fix drag into files instead of folder
  - Fix renaming sometimes breaking

### Which issue(s) this PR fixes 🔨

- Resolve #428

### CODE REVIEW

**Review by stavares843 — COMMENTED** [review]
image


in this PR you can add 2 folders with the same name, in dev it does not allow that behavior


dev

**Comment by luisecm** [comment]
Found one more bug on this branch

1. Create a new folder lets say "test"
2. Create another folder lets say "test2"
3. Enter to "test" folder and nothing is shown on tree and also you can no longer upload files

https://github.com/user-attachments/assets/5e1afab2-d40a-4454-bb0b-8f13553b1aec

**Comment by Flemmli97** [comment]
> Found one more bug on this branch
> 
> 1. Create a new folder lets say "test"
> 2. Create another folder lets say "test2"
> 3. Enter to "test" folder and nothing is shown on tree and also you can no longer upload files
> 
>  Grabacion.de.pantalla.2024-09-02.a.la.s.2.19.40.p.m.mov

regarding the file tree thats also how it works in dev. it only shows the file tree from current downwards
regarding uploading files... strange. that still works for me. can you show the logs?

**Comment by luisecm** [comment]
> > Found one more bug on this branch
> > 
> > 1. Create a new folder lets say "test"
> > 2. Create another folder lets say "test2"
> > 3. Enter to "test" folder and nothing is shown on tree and also you can no longer upload files
> > 
> > Grabacion.de.pantalla.2024-09-02.a.la.s.2.19.40.p.m.mov
> 
> regarding the file tree thats also how it works in dev. it only shows the file tree from current downwards. (though current folder should also show which it does for me) regarding uploading files... strange. that still works for me. can you show the logs?

Hey @Flemmli97 Revalidated now with latest commits from branch and I cannot see the issue now. Will add a ticket for fixing the tree folder structure in dev.

**Review by luisecm — APPROVED** [review]

**Review by InfamousVague — APPROVED** [review]

**Comment by luisecm** [comment]
Hey  @Flemmli97 I noticed one bug being introduced on this branch, user is able to create folders with empty name. Thats the reason this test is failing - F8 - If user tries to create a folder with empty name or press Esc while name input is displayed, folder is not created

image

**Comment by Flemmli97** [comment]
fixed

**Pull request merged**
