### PR TITLE
feat(profile): add PIN confirmation for account deletion and enhance settings UI

### LINKED ISSUE #848: task(DeleteAccount): Require that PIN be typed in before account is deleted
**Issue:**
We have the option to delete your account located on the PIN page and in Settings/Profile. We should make it a requirement that the user types in their pin # after they click _delete account_ but before account is actually deleted. Just as a precaution since this action would be permanent and unable to be reversed 

*If its too much to add in the Settings/Profile maybe we can ask the user "Are you sure you want to do this? This action cannot be reversed" or something like that. Best to discuss with @XileHorizon 

**Screenshots:**
Screenshot 2024-11-12 at 2 20 59 PM

Screenshot 2024-11-12 at 2 21 55 PM

### PR DESCRIPTION
**Pull request by lgmarchi**
#### 1. Change delete account button to red (Showing that is a dangerous action)

  <details><summary>Image</summary>
  <p>
  
 image

  </p>
  </details> 

#### 2. Add modal when user click on delete account button on profile page

- If user type wrong pin, it will show a error toast message: 

    <details><summary>Video showing behavior</summary>
    <p>
    
    https://github.com/user-attachments/assets/0f4b4e56-ba84-4c92-a3f6-4402e1ddf564
    

    
    </p>
    </details> 

- If user type correct pin, it will delete account permanently:

    <details><summary>Video showing behavior</summary>
    <p>
    
    https://github.com/user-attachments/assets/b682d8e0-f06e-400b-8261-9e7cc62f4210
    
    </p>
    </details> 

### Which issue(s) this PR fixes 🔨

-   Resolve #848

### CODE REVIEW

**Review by stavares843 — CHANGES_REQUESTED** [review]
missing asking pin on the pin page as phil mentioned here
https://github.com/Satellite-im/UplinkWeb/issues/848


video

https://github.com/user-attachments/assets/df5e63f9-e23b-4ebe-b0a1-5a6e387f956e



browser - chrome

**Comment by lgmarchi** [comment]
> missing asking pin on the pin page as phil mentioned here #848
> 
> video
> 
>  Gravacao.do.ecra.2024-11-13.as.16.35.20.mov 
> browser - chrome

Added.

**Review by stavares843 — APPROVED** [review]
so if you sign up > pin page > dont add a pin > delete account > will ask you a pin but there is no pin defined yet but if you add any pin deletes the account regardless

im fine with improving this later


one suggestion would be, maybe if no pin is defined yet while user is still on sign up, dont ask pin

https://github.com/user-attachments/assets/f0563154-d1b6-4575-a6ed-8f5dbf5365ef

**Comment by stavares843** [comment]
just let me know if you wanna address that here or on another PR @lgmarchi to know if we should add another ticket

**Review by phillsatellite — APPROVED** [review]

**Review by stavares843 — CHANGES_REQUESTED** [review]
just let me know if you wanna address that here or on another PR @lgmarchi to know if we should add another ticket

**Comment by lgmarchi** [comment]
> just let me know if you wanna address that here or on another PR @lgmarchi to know if we should add another ticket

I did changes you requested following your suggestion.

**Review by stavares843 — APPROVED** [review]

**Review by ashneverdawn — APPROVED** [review]

**Pull request merged**
