### PR TITLE
feat(chats): unreads

### LINKED ISSUE #419: feat(Notification): Wire up unreads to Warp
**Task:**
We have everything written up in the UI for unread messages/incoming friend requests we want to tie all of that up in Warp so we can have the unread message counter and incoming friend request counter as well 

**Screenshot:**
Screenshot 2024-08-15 at 12 59 08 PM

### LINKED ISSUE #486: bug(Chat): Scroll will jump to bottom of the chat
**Issue:**
There is a certain point in chat when you are scrolling down it will glitch and automatically jump to the bottom 

**Screen recording:**

https://github.com/user-attachments/assets/8fcb7f1c-75ef-4613-9857-fb0ac1c207ea

### LINKED ISSUE #683: task(Chats): Add count indicator for incoming messages
**Issue:**
When the user gets a new message we should show an indicator that counts how many unread messages the user has. It should match the same style of the one we have for incoming friend requests 

Screenshot 2024-10-07 at 4 34 55 PM

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Adds unread feature:
  - Wireup unread badge for chat button in navigation bar to display unread messages. Only gets triggered if not viewing the chat
  - Add unread feature in chat:
    - Adds a separator for unread messages in chat with date
    - Adds an indicator at the top of chat for amount of unread messages in chat
- Reduce the threshold where chat scrolls down (#486, see if thats better now. the feature itself is there to automatically scroll down whenever chat changes for incoming messages)

### Which issue(s) this PR fixes 🔨

- Resolve #486
- Resolve #419
- Resolve #683

### CODE REVIEW

**Comment by phillsatellite** [comment]
Hey Flem! So far this is working awesome theres just a little thing I wanted to mention. (I can create a new ticket if you'd rather fix in there) But it seems like separator for new unread messages will only cover half of the chat width and has a little ui issue with those black areas that appear on it. Other than that its working very well 

Screenshot 2024-10-08 at 12 48 36 PM
Screenshot 2024-10-08 at 12 48 24 PM

**Comment by Flemmli97** [comment]
that thing on top is not the separator. but it is broken. what browser you using?

**Comment by stavares843** [comment]
Captura de ecrã 2024-10-08, às 22 16 15


brave browser @Flemmli97

**Comment by phillsatellite** [comment]
Also replicated on Chrome as well

**Comment by stavares843** [comment]
same on opera

image

**Review by lgmarchi — APPROVED** [review]

**Review by stavares843 — COMMENTED** [review]
https://github.com/user-attachments/assets/df9b0063-5770-40d0-8810-4b19179195e4


when i go to the chat, i dont know which messages are unread

phil gets this but that does not appear on my side

image



browser - opera

**Review by stavares843 — COMMENTED** [review]
if im on the chat, and im scrolled up and i get new messages, theres no banner with the unreads

discord has this

image

**Review by stavares843 — COMMENTED** [review]
why does this badge does not have a number of unreads?

image


i know we have the unreads overall number on the bottom but if i have 20 chats, 23094309 unreads, i dont know how many unreads each chat with unreads has

**Review by stavares843 — COMMENTED** [review]
i only get this banner with the unreads first time starting a chat

image


after that i only get the unread dot on the sidebar

**Comment by Flemmli97** [comment]
> if im on the chat, and im scrolled up and i get new messages, theres no banner with the unreads
> 
> discord has this
> 
> image

unreads doesnt appear if you are viewing the chat

**Comment by Flemmli97** [comment]
> 3294293349009.mov 
> 
> when i go to the chat, i dont know which messages are unread
> 
> phil gets this but that does not appear on my side
> 
> image
> 
> browser - opera

i didnt know that dot was supposed to be unread Oo (i didnt add that) but i can fix that

**Comment by Flemmli97** [comment]
> why does this badge does not have a number of unreads?
> 
> image
> 
> i know we have the unreads overall number on the bottom but if i have 20 chats, 23094309 unreads, i dont know how many unreads each chat with unreads has

i didnt know that dot was supposed to be unread Oo (i didnt add that) but i can fix that

**Comment by stavares843** [comment]
> unreads doesnt appear if you are viewing the chat

but is that on purpose?

**Comment by Flemmli97** [comment]
> > unreads doesnt appear if you are viewing the chat
> 
> but is that on purpose?

yes. do we want to change that?

also for the badge on the sidebar: it seems that is also intended. like there is a boolean with `simpleUnreads` which is turned on. and if off will show the number

**Comment by stavares843** [comment]
> unreads doesnt appear if you are viewing the chat




if you are scroll up id'd say yes

**Review by stavares843 — APPROVED** [review]

**Review by phillsatellite — APPROVED** [review]

**Pull request merged**
