### PR TITLE
fix(Storage): Fix upload files on mobile for storage

### PR DESCRIPTION
**Pull request by lgmarchi**
### What this PR does 📖

This pull request includes changes to the file upload functionality in the `src/routes/files/+page.svelte` file. The modifications aim to streamline the file selection process and improve the user experience.

Improvements to file upload functionality:

* [`src/routes/files/+page.svelte`](diffhunk://#diff-bae6ecdcbd9bb6f2484c09f1f1807bfd39cb566f5f265eb3a2b4f9513d3771b5L379-R379): Refactored the `onFileSelected` function to take `target` directly as an `HTMLInputElement` parameter instead of extracting it from the event object.
* [`src/routes/files/+page.svelte`](diffhunk://#diff-bae6ecdcbd9bb6f2484c09f1f1807bfd39cb566f5f265eb3a2b4f9513d3771b5L630-R646): Replaced the existing file input element with a dynamically created input element for file uploads. This change includes creating the input element programmatically, setting its attributes, adding an event listener for the `change` event, and removing the element from the DOM after the file selection is complete.

### Which issue(s) this PR fixes 🔨

-   Resolve #

### CODE REVIEW

**Review by stavares843 — CHANGES_REQUESTED** [review]
so i did
- git checkout fix-storage-on-mobile
- git pull
- npm i
- npm run build
- npx cap sync  
- npx cap open ios
- compiled to a real iPhone
- went to files
- upload files


mp4 video of 7.5MB - does not appear
pdf file of 38MB - does not appear
pdf file of 98KB - appears
image of 1.9MB - appears

so it seems only gets uploaded if is very very small

**Comment by lgmarchi** [comment]
> so i did
> 
> * git checkout fix-storage-on-mobile
> * git pull
> * npm i
> * npm run build
> * npx cap sync
> * npx cap open ios
> * compiled to a real iPhone
> * went to files
> * upload files
> 
> mp4 video of 7.5MB - does not appear pdf file of 38MB - does not appear pdf file of 98KB - appears image of 1.9MB - appears
> 
> so it seems only gets uploaded if is very very small

I have tested again, no problem with large files. 

<details><summary>iOS</summary>
<p>

image

</p>
</details> 

<details><summary>Android</summary>
<p>

image

</p>
</details>

**Comment by luisecm** [comment]
@lgmarchi @stavares843 maybe not related to this ticket but what is the file size limit? I get "file size exceeded errors" in web and app for "big files' like greater of 150 mb


https://github.com/user-attachments/assets/af04ee1b-5370-4511-811f-8084a35b7b49

**Comment by luisecm** [comment]
@lgmarchi @stavares843 File size exceeded error shows for the same file in web dev, so I believe file uploads are good. Now, we need to test this PR with files sharing on chats, but friend requests are broken at the moment. Once that friend requests are stable again, we will test this part and if its all good we can approve

**Comment by lgmarchi** [comment]
> @lgmarchi @stavares843 File size exceeded error shows for the same file in web dev, so I believe file uploads are good. Now, we need to test this PR with files sharing on chats, but friend requests are broken at the moment. Once that friend requests are stable again, we will test this part and if its all good we can approve

I will change PR name, but I think is better to open other PR to send files on chats and we approve this one first.

**Review by phillsatellite — APPROVED** [review]

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
