### PR TITLE
fix(typingindicator): Fix typing area and add new styling

### LINKED ISSUE #577: bug(Chat): Typing indicator missing
**Issue:**
Looks like we regressed the typing indicator its missing on both 1on1 chats and group chats

**Screen recording:**

https://github.com/user-attachments/assets/952f1338-9ab4-4479-aeab-80b7360615d1

Luis received got this error message sent to him from github and we thought maybe this could be related 

image

### PR DESCRIPTION
**Pull request by Jekrimo**
### What this PR does 📖

- Got user typing indicator working, did some light css to get it to an appropriate area

### Which issue(s) this PR fixes 🔨

- Resolve #577 

### Special notes for reviewers 🗒️

The only thing I haven't been able to test is multiple users typing

### CODE REVIEW

**Comment by stavares843** [comment]
when doing `npm run build` is adding this warning


```
190a191,197
> 4:34:14 PM [vite-plugin-svelte] /home/runner/work/UplinkWeb/UplinkWeb/src/lib/components/messaging/PendingMessageGroup.svelte:138:0 Unused CSS selector ".pending-message-group .pending-message-buffer"
> 136:   flex-direction: column;
> 137: }
> 138: .pending-message-group .pending-message-buffer {
>      ^
> 139:   width: var(--input-height);
> 140: }
```


does not happen on dev

**Comment by Jekrimo** [comment]
Hey @stavares843 ! I deleted and pushed that unused class, do you know if it's still showing it's messed up? commit was '[build log fix unused class](https://github.com/Satellite-im/UplinkWeb/pull/639/commits/cdbef15603be192ff0dc304d0975787cf2045455)'

**Comment by stavares843** [comment]
checking

**Comment by stavares843** [comment]
no more warning 🎉

**Comment by Jekrimo** [comment]
@stavares843 Yay! Thank you for checkin!!

**Comment by phillsatellite** [comment]
Hey Jeff! Noticed one thing brotha, if you have more than 1 friend in the sidebar whenever one of your friends types the indicator appears for everyone on the sidebar

https://github.com/user-attachments/assets/df6865b4-e5f6-4000-bfd2-b0a1fbad8502

**Comment by Jekrimo** [comment]
Super weird! Lookin into it now, thanks Phillerosa!

**Comment by phillsatellite** [comment]
Retested Jeffs commit for the fix and issue is still happening. Reached out to him to let him know

**Comment by Jekrimo** [comment]
Hey @phillsatellite can I get you to test this again today? I added an extra call and *seems* to be functioning correctly, although, I have had a rare bug where the typing indicator sticks around after a message is sent but I think this only happens when the messages aren't sending correctly when a change in the code goes through and the reload happens on the app.

**Comment by phillsatellite** [comment]
Did some testing for Jeff and I did replicate the bug he mentioned. It seemed to happen when I had more than 1 chat in the sidebar

https://github.com/user-attachments/assets/37472bec-6d2f-4ba1-803f-40713e65d75f

**Review by InfamousVague — APPROVED** [review]

**Comment by Jekrimo** [comment]
Hey @phillsatellite ! I'm testing this again this morning and it seems the bug that causes the chat to move up in the sidebar when a typing indicator comes through is working again! At least on my machine - famous last words - would you be so kind as to check it out today?

**Comment by phillsatellite** [comment]
Hey @Jekrimo So I did some more testing (I double checked myself like 30 times to be sure I had the latest, did all new profiles etc) but still getting that bug when a friend is typing to you if you have more than one chat the typing indicator will appear on every chat and persist for a pretty long time after friend stops typing 

https://github.com/user-attachments/assets/ca220ea7-38d2-4ce8-bfa6-47f9662f36c9

**Review by phillsatellite — APPROVED** [review]

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
