### PR TITLE
feat(PFP): Fallback identicons for profiles without a picture

### PR DESCRIPTION
**Pull request by InfamousVague**
### What this PR does 📖

image

### CODE REVIEW

**Comment by luisecm** [comment]
@InfamousVague I see that 3 moderate severity vulnerabilities are popping up now when running npm install, probably associated to this new dependency added: @metamask/jazzicon

image

**Comment by luisecm** [comment]
@InfamousVague one more thing, when I remove the profile picture, I see that a 404 error appears in console for profile picture not found:

image

**Comment by luisecm** [comment]
@InfamousVague Enable Gamepad settings description is not showing correctly:

image

**Comment by InfamousVague** [comment]
> Do we want the user to be able to also clear the fallback identicon? If not I can create another ticket rather than holding up this 👍
> 
>  Screen.Recording.2024-07-10.at.10.32.48.AM.mov

Nah, I think the identicon is better than the broken imagfe

**Comment by InfamousVague** [comment]
> @InfamousVague Enable Gamepad settings description is not showing correctly:
> 
> image

I'll address this in an upcoming PR if that's okay (the next PR will be specific for controller)

**Comment by InfamousVague** [comment]
> @InfamousVague I see that 3 moderate severity vulnerabilities are popping up now when running npm install, probably associated to this new dependency added: @metamask/jazzicon
> 
> image

Unfortunately this will require an upstream fix from metamask, however I don't think there is anything security related that could be introduced by this.

**Review by luisecm — APPROVED** [review]

**Comment by luisecm** [comment]
All comments have been addressed and two new tickets were created to handle these a separate bugs:

https://github.com/Satellite-im/UplinkWeb/issues/244
https://github.com/Satellite-im/UplinkWeb/issues/243

**Pull request merged**
