### PR TITLE
feat(ui): Upload + download files chat

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Implements file download for chat
  - a blob and dummy element is created to prompt the user to download the file. see https://github.com/Satellite-im/UplinkWeb/pull/139/files#diff-a3d58510045e955ae85f6e2b5a245faeb5606afb292433e3620d69207d9a5da2R569.  
  Maybe there is a way to directly prompt the stream download? As this way the prompt will only appear after the stream is processed which can be relevant for large files
- Fixes some stuff in #115 with the upload progress
  - It seems thumbnail data is missing on uploaded images. If this is the case for now the file will be displayed as a generic file instead of image preview
  - It seems the total size is missing during upload stream process so the progress bar will not work correctly atm

### CODE REVIEW

**Review by stavares843 — COMMENTED** [review]
I tested out with @phillsatellite and when I sent files to @phillsatellite basic png's and stuff, he got those and opened fine

the ones @phillsatellite sent to me, never arrived on my mac

macOS, ventura

browser - Chrome

**Comment by Flemmli97** [comment]
can you post the console logs?

**Comment by stavares843** [comment]
i believe @phillsatellite sent out small files though

**Comment by Flemmli97** [comment]
what about the logs on @phillsatellite side?

**Comment by stavares843** [comment]
@phillsatellite and i retested, and now we both are getting the files when we sent

**Review by InfamousVague — APPROVED** [review]

**Review by InfamousVague — APPROVED** [review]
👍

**Pull request merged**
