### PR TITLE
fix(Navigation): Improve navigation using bottom nav bar on mobile

### PR DESCRIPTION
**Pull request by lgmarchi**
### What this PR does 📖

-  Improve navigation using bottom nav bar on mobile

### Which issue(s) this PR fixes 🔨

-   Resolve #

### CODE REVIEW

**Comment by luisecm** [comment]
@lgmarchi Hey Lucas, automation tests caught one bug on this branch:
1. Open in mobile view
2. Click on create group chat
3. Create group modal is not visible until you swipe to the right (like in the video from the example):

https://github.com/user-attachments/assets/770b3c3a-942d-45ff-93f5-10359748a85c

Currently in dev, if you are on mobile view and then click on Create group, you can see the create group modal without having to swipe

**Comment by lgmarchi** [comment]
> @lgmarchi Hey Lucas, automation tests caught one bug on this branch:
> 
> 1. Open in mobile view
> 2. Click on create group chat
> 3. Create group modal is not visible until you swipe to the right (like in the video from the example):
> 
>  Grabacion.de.pantalla.2024-12-06.a.la.s.2.21.38.p.m.mov 
> Currently in dev, if you are on mobile view and then click on Create group, you can see the create group modal without having to swipe



> @lgmarchi Hey Lucas, automation tests caught one bug on this branch:
> 
> 1. Open in mobile view
> 2. Click on create group chat
> 3. Create group modal is not visible until you swipe to the right (like in the video from the example):
> 
>  Grabacion.de.pantalla.2024-12-06.a.la.s.2.21.38.p.m.mov 
> Currently in dev, if you are on mobile view and then click on Create group, you can see the create group modal without having to swipe

Fixed.

**Comment by stavares843** [comment]
@lgmarchi could you add which PR is this one waiting for please, for us to know when merging

**Comment by lgmarchi** [comment]
Waiting PR #925

**Comment by phillsatellite** [comment]
Noticed some issues. These issues are able to be replicated on both Android & iOS. Both were new accounts on brand new builds 

- navbar appears through the entire Account Creation process 
image

-navbar will persist while keyboard is open and overlap the cancel/continue buttons 
image

- After you enter into a chat and you open the sidebar the navbar will disappear and there is no way for the user to bring it back 
image

- Within Settings any page that user is able to scroll in, the navbar will overlap whatever content is at the end of the page 

About
image

Audio
image

Gamepad
image

Profile
image

**Review by phillsatellite — APPROVED** [review]

**Review by ashneverdawn — APPROVED** [review]

**Pull request merged**
