### PR TITLE
fix(chat): update emoji picker

### LINKED ISSUE #614: bug(emojis): skin tone selected is not preserved after closing emoji picker
1. Open emoji picker and choose skin tone
2. Close emoji picker
3. Open it again and you will see that skin tone previously selected is not preserved

On chat apps this should be store so the user does not have to pick it up every time it opens the emoji picker

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Remove duplicate emoji counter that already existed in UIStore
- Make skintone selection persistent 

### Which issue(s) this PR fixes 🔨

- Resolve #614

### CODE REVIEW

**Comment by phillsatellite** [comment]
Sara and I did some testing together and we both had the same behavior we select skin tone but it is not applied to selected emoji. 

We tested this on Chrome, Brave, Safari and Opera 

https://github.com/user-attachments/assets/95abc7bf-0358-40e5-acd0-af0ead9c74cd

**Comment by luisecm** [comment]
@Flemmli97 There is one automated test currently failing on your branch because the Frequently Used emojis have 5 now by default and therefore the count of emojis frequently used test is not matching with the current expectation from the tests. I have a PR to update the tests in case your pr is merged - https://github.com/Satellite-im/automated-tests-web/pull/179

**Comment by Flemmli97** [comment]
> @Flemmli97 There is one automated test currently failing on your branch because the Frequently Used emojis have 5 now by default and therefore the count of emojis frequently used test is not matching with the current expectation from the tests. I have a PR to update the tests in case your pr is merged - [Satellite-im/automated-tests-web#179](https://github.com/Satellite-im/automated-tests-web/pull/179)

ye we kinda duplicated the stuff there. we already had a "freq used" data saved (emoji counter)

**Comment by Flemmli97** [comment]
> Sara and I did some testing together and we both had the same behavior we select skin tone but it is not applied to selected emoji.
> 
> We tested this on Chrome, Brave, Safari and Opera
> 
>  Screen.Recording.2024-10-10.at.1.18.50.PM.mov

those emoji do not have skin colors. scroll down a bit

**Review by phillsatellite — APPROVED** [review]

**Review by lgmarchi — APPROVED** [review]

**Pull request merged**
