### PR TITLE
chore(dependency): update wasm to 1.5.1

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Updates wasm to 1.5.1

### Special notes for reviewers 🗒️

- Group permission was redone and is now user based instead of global. We need to adjust the ui before we can make use of that. For this PR i disabled group permission modification

### CODE REVIEW

**Review by lgmarchi — APPROVED** [review]

**Review by InfamousVague — APPROVED** [review]

**Review by dariusc93 — APPROVED** [review]

**Comment by luisecm** [comment]
@Flemmli97 Hey Kevin, I noticed the following error caught by the automated tests when removing the seed phrase:

This error is not happening in dev

https://github.com/user-attachments/assets/1d5c3b68-4e28-4e04-8188-b6fa88c2074b

image

**Comment by phillsatellite** [comment]
This seems to break chats. When you try to start one nothing happens and you get errors in console (see image below) Haven't been able to test anything in chats due to this 

https://github.com/user-attachments/assets/0f020834-2ad1-474e-b115-e35d52cbdad5

Screenshot 2024-11-05 at 11 02 35 AM

**Comment by luisecm** [comment]
> @Flemmli97 Hey Kevin, I noticed the following error caught by the automated tests when removing the seed phrase:
> 
> This error is not happening in dev
> 
>  Grabacion.de.pantalla.2024-11-04.a.la.s.5.57.35.p.m.mov 
> image

I see that this is fixed in the latest commit, thanks! @Flemmli97

**Comment by Flemmli97** [comment]
> This seems to break chats. When you try to start one nothing happens and you get errors in console (see image below) Haven't been able to test anything in chats due to this
> 
>  Screen.Recording.2024-11-05.at.11.03.21.AM.mov 
> 
> Screenshot 2024-11-05 at 11 02 35 AM



> This seems to break chats. When you try to start one nothing happens and you get errors in console (see image below) Haven't been able to test anything in chats due to this
> 
>  Screen.Recording.2024-11-05.at.11.03.21.AM.mov 
> 
> Screenshot 2024-11-05 at 11 02 35 AM

have you updated the packages? cause that method is in newer wasm.
try deleting the `node_modules` folder and run `npm i`

**Review by phillsatellite — APPROVED** [review]

**Pull request merged**
