### PR TITLE
feat(Chat): Possible to get files from storage to send on chats

### LINKED ISSUE #398: feat(Browse Files): Allow browsing locally stored files within uplink and send in chat.

### LINKED ISSUE #559: task(Chat): Wire up Browse Files
**Task:**
We want to wire up the Browse Files button when sending files in chat. When the user clicks this it should open up a modal of all the files you have uploaded on Uplink and allow you to select one or multiple files to send in the chat 

**Screenshot:**
image

### PR DESCRIPTION
**Pull request by lgmarchi**
### What this PR does 📖

- Possible to get files from storage to send on chats
- Attachments now are persistent, we can move to other page, other chat, and attachments will keep same for that specific chat

### Which issue(s) this PR fixes 🔨

- Resolve #559 
- Resolve #398

### CODE REVIEW

**Comment by luisecm** [comment]
I am seeing an issue in your PR @lgmarchi - the send button from chat sometimes does nothing 
1. Send a message from user A to user B
2. User B received message
3. User B types something in chat bar input
4. User B clicks on Send Button to send text written in chatbar but nothing happens
5. Also, write a message in chatbar in press Enter key, message is not sent

**Review by ashneverdawn — APPROVED** [review]

**Review by InfamousVague — APPROVED** [review]

**Comment by luisecm** [comment]
I am having friend request issues in this branch - with automation and manual testing

**Comment by InfamousVague** [comment]
I am getting a small bug, when picking the file to send I chose the file, hit send and it does not show the file above the chatbar. Once I refresh the page however the file exists.

**Comment by phillsatellite** [comment]
> I am getting a small bug, when picking the file to send I chose the file, hit send and it does not show the file above the chatbar. Once I refresh the page however the file exists.

Luis and I verified this and were able to replicate - we also noticed if you use this flow below that when you try to upload the file again it will appear twice in the chatbar 

- open upload file and select test.txt file (example name)
- on preview of send files remove the preview icon
- open upload file and pickup the same file (file wont show)
- upload file again and will show twice

**Comment by phillsatellite** [comment]
Sent Lucas a DM it seems like after you send a file if you try to select the same one and send it again it will not send. He replicated and is going to take a look into it 

https://github.com/user-attachments/assets/0183bb30-7e87-4af6-85a7-0b8b8efa7c57

**Comment by luisecm** [comment]
@lgmarchi There is an issue when picking up more than one file from local machine to send on chat. 


https://github.com/user-attachments/assets/e4f10d63-486d-4eda-983e-0c9bb72468d1

1. Go to chat
2. Select upload files
3. Choose upload from local files
4. Pick up more than one file on your local machine
5. Preview is not loaded (bug)
6. Refresh screen and you will see that sometimes the message is sent and even appears only on remote or local side instead of both sides

**Review by phillsatellite — APPROVED** [review]

**Pull request merged**
