### PR TITLE
feat(Call): Enable screen share on calls.

### LINKED ISSUE #853: task(Calling): Add screenshare feature into calling
**Task:**
Just like we had in core we want to add the ability for the user to share their screen to other users while in a call

### PR DESCRIPTION
**Pull request by lgmarchi**
### What this PR does 📖

This pull request introduces the screen sharing feature in the calling component of the application. The changes include updates to the `CallScreen.svelte` file to handle screen sharing UI and state management, as well as modifications to the `Voice.ts` file to manage screen sharing logic.

Changes to `CallScreen.svelte`:

* Added a new state variable `screenShareEnabled` and subscribed to its changes from the store. [[1]](diffhunk://#diff-7fb298436c145f100a88f4894f81ebbe77b50f1630c0907218b81ca5dbad840fR33) [[2]](diffhunk://#diff-7fb298436c145f100a88f4894f81ebbe77b50f1630c0907218b81ca5dbad840fR131-R136)
* Updated the UI to conditionally display video elements based on the `screenShareEnabled` state. [[1]](diffhunk://#diff-7fb298436c145f100a88f4894f81ebbe77b50f1630c0907218b81ca5dbad840fL349-R368) [[2]](diffhunk://#diff-7fb298436c145f100a88f4894f81ebbe77b50f1630c0907218b81ca5dbad840fL360-R378) [[3]](diffhunk://#diff-7fb298436c145f100a88f4894f81ebbe77b50f1630c0907218b81ca5dbad840fL372-R399) [[4]](diffhunk://#diff-7fb298436c145f100a88f4894f81ebbe77b50f1630c0907218b81ca5dbad840fL404-R437) [[5]](diffhunk://#diff-7fb298436c145f100a88f4894f81ebbe77b50f1630c0907218b81ca5dbad840fL417-R447) [[6]](diffhunk://#diff-7fb298436c145f100a88f4894f81ebbe77b50f1630c0907218b81ca5dbad840fL448-R500)
* Modified the button appearance and functionality to toggle screen sharing.

Changes to `Voice.ts`:

* Added `screenShareEnabled` to the `VoiceRTCOptions` and `VoiceRTCUser` types. [[1]](diffhunk://#diff-a75896c18790a15b7e0ae422d555a80c3e09067296e47a5dcc6891ab3385dfb4R65-R67) [[2]](diffhunk://#diff-a75896c18790a15b7e0ae422d555a80c3e09067296e47a5dcc6891ab3385dfb4R78)
* Updated the `Participant` and `CallRoom` classes to include `screenShareEnabled`. [[1]](diffhunk://#diff-a75896c18790a15b7e0ae422d555a80c3e09067296e47a5dcc6891ab3385dfb4R182) [[2]](diffhunk://#diff-a75896c18790a15b7e0ae422d555a80c3e09067296e47a5dcc6891ab3385dfb4R325)
* Implemented screen sharing logic in the `VoiceRTC` class, including methods to start and stop screen sharing. [[1]](diffhunk://#diff-a75896c18790a15b7e0ae422d555a80c3e09067296e47a5dcc6891ab3385dfb4R361-R363) [[2]](diffhunk://#diff-a75896c18790a15b7e0ae422d555a80c3e09067296e47a5dcc6891ab3385dfb4R412-R426) [[3]](diffhunk://#diff-a75896c18790a15b7e0ae422d555a80c3e09067296e47a5dcc6891ab3385dfb4R507-R563) [[4]](diffhunk://#diff-a75896c18790a15b7e0ae422d555a80c3e09067296e47a5dcc6891ab3385dfb4R933-R937) [[5]](diffhunk://#diff-a75896c18790a15b7e0ae422d555a80c3e09067296e47a5dcc6891ab3385dfb4R962)

Changes to `Store.ts`:

* Added a new writable state `screenShare` to manage screen sharing state.
* Added a method `updateScreenShareEnabled` to update the screen sharing state.

Changes to `initial.ts`:

* Added `screenShare` to the `IState` interface.

> [!NOTE]
>  1. Screen share has more priority than camera enable, so when user share screen, his camera stream will be changed to share screen.
> 2. User can enable and disable camera during share screen, the result we can see after user disable share screen. 
> 3. User should be able to go out from chat, back to it, and keep share screen all the time.  

### Which issue(s) this PR fixes 🔨

-   Resolve #853

### CODE REVIEW

**Review by InfamousVague — APPROVED** [review]

**Review by stavares843 — CHANGES_REQUESTED** [review]
https://github.com/user-attachments/assets/bb60c231-0eb1-4417-841c-6fb9bdf1f75a

so the first call i did, i clicked on stream and i was able to select a chrome tab to screenshare

but it never appeared to the other user

then i hang up the call, made a new call - the stream button was already green by default not sure why, and clicking again i was not able to select any window/tab to screenshare

and it never appeared on the other user, was always black

browser - chrome

**Comment by lgmarchi** [comment]
> 82382389289.mov 
> so the first call i did, i clicked on stream and i was able to select a chrome tab to screenshare
> 
> but it never appeared to the other user
> 
> then i hang up the call, made a new call - the stream button was already green by default not sure why, and clicking again i was not able to select any window/tab to screenshare
> 
> and it never appeared on the other user, was always black
> 
> browser - chrome

@stavares843 I did a code to improve UI state, but this problem to not arrive to other user I didn't have. 

Maybe are you using private tab and some permissions are denied? 


<details><summary>Video showing example working</summary>
<p>

https://github.com/user-attachments/assets/4592b2ad-80c5-4908-88c8-e0a445c7d21c

</p>
</details>

**Comment by stavares843** [comment]
the user that was sharing the screen was not in private browser, the other user was in private browser

will try again

**Comment by luisecm** [comment]
@lgmarchi The automated test failing against this PR is fixed in here - https://github.com/Satellite-im/automated-tests-web/pull/194 Currently it validates that CSS background color from button of screen share changes to red after clicking on it. However this is changing on the current PR to green, you can see the tests updated passing now and I will merge my PR in automated tests repo once yours is merged

**Review by stavares843 — APPROVED** [review]

**Review by phillsatellite — APPROVED** [review]

**Pull request merged**
