### PR TITLE
feat(Communities): Mock communities settings UI.

### PR DESCRIPTION
**Pull request by InfamousVague**
### What this PR does 📖

This PR contains the UI for many of the community settings pages.

### CODE REVIEW

**Comment by InfamousVague** [comment]
image
image
image
image

**Comment by stavares843** [comment]
very neat! 🎉

**Comment by InfamousVague** [comment]
This is ready for test, this doesn't do anything yet but you can view the changes by enabling devmode and clicking the Satellite community icon in the slimbar. For testing we should just be sure this doesn't break anything.

**Comment by luisecm** [comment]
The failing automated test can be ignored since its a snapshot validation, that will require update due to the layout changes

**Pull request merged**
