### PR TITLE
feat(Mobile-Navigation): Add Bottom Navigation Bar for mobile

### LINKED ISSUE #907: Improve navigation on mobile using bottomNavBar

### PR DESCRIPTION
**Pull request by lgmarchi**
### What this PR does 📖

- Add bottom nav bar for mobile

https://github.com/user-attachments/assets/e17e6e44-4db1-4c5e-a045-c600e161d698

### Which issue(s) this PR fixes 🔨

-   Resolve #907

### CODE REVIEW

**Comment by luisecm** [comment]
@lgmarchi Hello Lucas, there is a bug in this branch - The install banner is not shown on web version and therefore the automated tests are failing due to this (one before hook step on many of them is dismissing this banner on web)

**Review by stavares843 — CHANGES_REQUESTED** [review]
luis comment needs fixing

**Comment by stavares843** [comment]
we will retest with the latest PR that was merged

**Comment by phillsatellite** [comment]
Hey Lucas, I noticed a bug when testing 

- If the user adds a chat to their favorites the navBar will be missing. If they remove the user from their favorites the navBar will still be missing. User is forced to uninstall then reinstall and do a new account when this bug happens 

https://github.com/user-attachments/assets/99639279-732e-421a-956a-25817203ba66

**Comment by lgmarchi** [comment]
> Hey Lucas, I noticed a bug when testing
> 
> * If the user adds a chat to their favorites the navBar will be missing. If they remove the user from their favorites the navBar will still be missing. User is forced to uninstall then reinstall and do a new account when this bug happens
> 
>  Screen.Recording.2024-12-03.at.7.14.04.PM.mov

Interesting, I will take a look

**Comment by lgmarchi** [comment]
> Hey Lucas, I noticed a bug when testing
> 
> * If the user adds a chat to their favorites the navBar will be missing. If they remove the user from their favorites the navBar will still be missing. User is forced to uninstall then reinstall and do a new account when this bug happens
> 
>  Screen.Recording.2024-12-03.at.7.14.04.PM.mov

Fixed

**Review by phillsatellite — APPROVED** [review]

**Review by ashneverdawn — APPROVED** [review]

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
