### PR TITLE
feat(Install Banner): Added install banner, pending functionality to actually download

### PR DESCRIPTION
**Pull request by InfamousVague**
### What this PR does 📖
image

Right now this PR just displays a button depending on the operation system the user is on to instruct them to download the application locally.

### CODE REVIEW

**Comment by stavares843** [comment]
very cool!

**Comment by stavares843** [comment]
that seems a windows issue regarding the icon

i'd say we can either ditch the icon or replace the icon for a PNG asset or something

**Comment by InfamousVague** [comment]
@XileHorizon can you replace this icon?

**Comment by InfamousVague** [comment]
> Looks pretty good there's just two things I wanted to ask about (I can deff create tickets for these so we can get this merged in)
> 
> 1. On Windows the download icon looks a little odd compared to macOS
>    image
> 2. If the user clears out the banner at the top it will not re-appear after refresh. Do we want to have it re-appear to give the user another chance to be able to download? Or maybe have a spot in Settings the user can still download the app if they clear out that banner?

i had it stay hidden after they cleared it out intentionally but we could change it to if they close it three times or something

**Review by tooshel — APPROVED** [review]

**Comment by XileHorizon** [comment]
I fixed the WIndows Icon

**Pull request merged**
