### PR TITLE
fix(Call): Improve talking indicator for video and no video calls

### LINKED ISSUE #766: bug(Voice): Improve voice/video indicator
**Issue:**
The voice and video indicator in calls don't always appear when they should and could use some improving. Sometimes when a user speaks it'll flash the indicator for a second and then disappear and then randomly flash again for a moment 

**Screenshot:**

https://github.com/user-attachments/assets/0d23e747-15fa-40b5-8247-91866e5566bd

### PR DESCRIPTION
**Pull request by lgmarchi**
### What this PR does 📖

- Audio calls showing correct talking indicator now
image

- Video calls showing correct talking indicator now 
image

- Add more relays and increase relays redundancy to improve connections in calls

### Which issue(s) this PR fixes 🔨

- Resolve #766

### CODE REVIEW

**Review by ashneverdawn — APPROVED** [review]

**Review by stavares843 — COMMENTED** [review]
https://github.com/user-attachments/assets/cda87a8c-f13f-4ed1-aa8a-722623550fd8



@phillsatellite and i tested and when phil was talking, the flash appeared - the green border which seems the expected behavior, but then you will notice that phil is talking, im not talking and my user on phil side also got the flashing green border so that does not seem expected behavior

this happened on phil side and also on my side

so when phil was talking on my side was flashing the green border like my user was talking and it was not

we also noticed this error on the console browser 

Captura de ecrã 2024-11-06, às 18 25 56




browser - chrome

we did a new build, new account and all

**Comment by lgmarchi** [comment]
> 2093923902.mov 
> @phillsatellite and i tested and when phil was talking, the flash appeared - the green border which seems the expected behavior, but then you will notice that phil is talking, im not talking and my user on phil side also got the flashing green border so that does not seem expected behavior
> 
> this happened on phil side and also on my side
> 
> so when phil was talking on my side was flashing the green border like my user was talking and it was not
> 
> we also noticed this error on the console browser
> 
> Captura de ecrã 2024-11-06, às 18 25 56
> browser - chrome
> 
> we did a new build, new account and all

Talking indicator is not filtering just voice now, any sound will fire it.

**Comment by stavares843** [comment]
right I get that, but if that is the case, why did it flashed EXACTLY on my side when phil was talking?

also phil and i tested again and there was audio on my side and no green border, but for phil was fine

image



regardless, im fine with merging if you feel theres no more room for improvement

**Comment by lgmarchi** [comment]
> right I get that, but if that is the case, why did it flashed EXACTLY on my side when phil was talking?
> 
> also phil and i tested again and there was audio on my side and no green border, but for phil was fine
> 
> image
> 
> regardless, im fine with merging if you feel theres no more room for improvement

My tests with @phillsatellite worked great and with @tooshel as well.

**Comment by tooshel** [comment]
> My tests with @phillsatellite worked great and with @tooshel as well.

For me the call itself went though (after you changed the relays) but we did have issues with the green border going crazy on my side and not really working, right?

**Comment by lgmarchi** [comment]
> > My tests with @phillsatellite worked great and with @tooshel as well.
> 
> For me the call itself went though (after you changed the relays) but we did have issues with the green border going crazy on my side and not really working, right?

Actually it worked, now we can see in other ticket, why it goes crazy for you, but it was working when you were talking, and worked when I was talking.

**Comment by tooshel** [comment]
> Actually it worked, now we can see in other ticket, why it goes crazy for you, but it was working when you were talking, and worked when I was talking.

I mean, maybe this is better than what we had before and we should merge but it seems the spirit of the original issue was that the indicator didn't work for sender or receiver. We can always make a new ticket if this code adds value and makes SOMETHING better. It seemed to make calling itself better after you added relays but it could have also been a fluke.

**Pull request merged**
