### PR TITLE
feat(calling): add call join button

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- When starting a call send a message in chat
- Message will contain 2 join button (video, audio only) to join the call
  - This allows (re)joining the call without getting a call notification
  - Since calls are just rooms with connection users could join the call without any special setup already
- Fix "special" message parsing (e.g. end call message didnt work properly and could still be edited)

### CODE REVIEW

**Comment by phillsatellite** [comment]
Hey Kevin! Awesome feature! Theres just one thing I noticed during testing 

After the call has ended if the user clicks the rejoin call button in the message that is sent in chat it will put them in a call by themselves and never send a call notification to the other users. Should we block this action after everyone has left the call? 

https://github.com/user-attachments/assets/7a9f8e6f-e782-4003-8145-15c8e179eb7a

**Comment by Flemmli97** [comment]
> Hey Kevin! Awesome feature! Theres just one thing I noticed during testing
> 
> After the call has ended if the user clicks the rejoin call button in the message that is sent in chat it will put them in a call by themselves and never send a call notification to the other users. Should we block this action after everyone has left the call?
> 
>  Screen.Recording.2024-10-28.at.2.24.03.PM.mov

i think i mentioned in meeting already but there is no way to check if a call is in progress and at the same time no way if a call has ended. only way would be to search for "call ended" message but i feel like that is very brittle

**Review by phillsatellite — APPROVED** [review]

**Comment by stavares843** [comment]
>  but there is no way to check if a call is in progress



cant we reuse the same logic we use on the sidebar to display the ongoing call? that disappears when the call finishes as well and appears when is on progress and appears when it starts if you exit the chats

**Comment by Flemmli97** [comment]
> > but there is no way to check if a call is in progress
> 
> cant we reuse the same logic we use on the sidebar to display the ongoing call? that disappears when the call finishes as well and appears when is on progress and appears when it starts if you exit the chats

that is when you are in a call. if you are in a call then you know when the call ends. but if you arent in a call then you need to actually join the call to check the status of it

**Review by InfamousVague — APPROVED** [review]

**Pull request merged**
