### PR TITLE
fix(bug): can't login without clearing cache

### PR DESCRIPTION
**Pull request by ashneverdawn**
### What this PR does 📖

- Allows you to login without clearing cache

### Which issue(s) this PR fixes 🔨

- Relates to #80

### Special notes for reviewers 🗒️

The issue stems from the Logger missing some functions such as `debug` `warn` `error`. I'm not entirely sure why this happens, or why it only happens when we don't clear the cache. 

This PR detects this issue at the first occurrence and initializes the Logger properly. It also logs a warning message to indicate this happened. 

This doesn't address the underlying cause, but until we find it, we at least won't have to clear the cache every time we want to use the app to test things.

### CODE REVIEW

**Comment by InfamousVague** [comment]
Even if this doesn't fix the issue (though I think it's best to wait until Monday's meeting anyways to discuss) we can still merge this in to have better parity in the JS logger implementation and warp.

**Comment by ashneverdawn** [comment]
> * After creating an account I tried to logout and then log back in with the same account but get taken straight to Create an Account and then would infinite load with this error.
> 

^This is a separate issue - UplinkWeb likely doesn't properly detect the existing account, so instead it tries to create it which fails because it already exists.


> `warp_ipfs.js?v=5cabb949:4495 WebSocket connection to 'wss://146.190.184.59:4001/' failed:`
> 

^This error is actually unrelated and is a separate issue stemming from relay server. Behaviour isn't affected though and so this can be safely ignored. It will be solved on the Warp side.

> * After adding a profile/banner picture and username/status message I refreshed my browser and the status message changed to "status message unknown" (the first time I saw this bug it changed my username and status message to unknown but on later attempts it only changed the status message) If you try to change it again after you refreshed your browser you will get this error.
> 
> Screenshot 2024-06-14 at 11 45 04 AM
>  Screen.Recording.2024-06-14.at.11.36.30.AM.mov 

^Also a separate issue

> * If you upload files and then refresh the browser all of your files will be missing. If you try to re-upload them you will be returned this error.
> 
> Screenshot 2024-06-14 at 11 51 54 AM
>  Screen.Recording.2024-06-14.at.11.38.18.AM.mov

^ See issue #84  This happens because the unlock function that initializes stuff, like loading wasm, unlocking tesseract, etc, only gets called on auth screen. So when you refresh any page, nothing is setup and it's not actually connected to anything anymore.

**Comment by ashneverdawn** [comment]
> Even if this doesn't fix the issue (though I think it's best to wait until Monday's meeting anyways to discuss) we can still merge this in to have better parity in the JS logger implementation and warp.

I agree

**Comment by InfamousVague** [comment]
Looks good to me, just the merge conflict then feel free to merge!

**Comment by ashneverdawn** [comment]
fyi, I think by now I've got a pretty good idea of what's causing the underlying issue of the logger is sometimes missing functions. Merging this now to unblock people a bit. And I'm addressing the underlying issue in a subsequent PR I'm working on.

**Pull request merged**
