### PR TITLE
feat(settings): Seed phrase save

### LINKED ISSUE #379: bug(Settings): Phrases still visible after hiding
**Issue:**
In Settings/Profile if you hide your account phrases and then log out and log back in the phrases will still be visible 

**Screen recording:**

https://github.com/user-attachments/assets/d74600d2-cb8d-4807-91b4-d4933d0acef4

### LINKED ISSUE #396: Sending gifs does not work
- Gif picker opens but after clicking on a gif is never sent in chat
- When you start looking for a gif, clear input to search for another, and repeat this process at some point the gif picker and whole screen freezes and you have to refresh browser

### LINKED ISSUE #420: feat(Global): Add warning for seed phrases
**Issue:**
Right now we dont have a warning about saving seed phrases when you make an account. This ticket is to add that in

### LINKED ISSUE #426: feat(Chat): Show true size of pictures when previewing file
**Issue:**
When you preview pictures that were sent in chat its the same fixed size for each one. Instead we should show the true size like how we had it in native Uplink

**Screen recording:**

https://github.com/user-attachments/assets/9ddebaf8-d60e-4c08-8bc5-4b2b3af7ac3a

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Implement seed phrase save setting
  - If true phrase will be saved in tesseract and is fetchable (e.g. via the settings page)
  - If false no phrase will be saved
  - Turning off saving in settings page will delete the phrase from tesseract too. This comes with a warning
- Update wasm to 1.3.3
- Additionally increases thumbnail size to 500x500 (since its just one more line) which closes #426 

### Which issue(s) this PR fixes 🔨

- Resolve #379
- Resolve #426 
- Resolve #420
- Resolve #396

### CODE REVIEW

**Comment by stavares843** [comment]
so the conflict with the package is because we reverted to 1.3.2 on dev since friend requests were not working on 1.3.3

**Comment by Flemmli97** [comment]
waiting for #469

**Comment by stavares843** [comment]
@Flemmli97 

just merged https://github.com/Satellite-im/UplinkWeb/pull/469

**Comment by stavares843** [comment]
thank you 🎉

**Comment by stavares843** [comment]
https://github.com/user-attachments/assets/6f0cb791-fa2a-41f2-9f5f-fe1b1d7b3555

flow
- i switched to this branch
- npm i
- npm run dev
- made a new account
- going to settings appears like that

chrome, macOS

**Comment by Flemmli97** [comment]
try deleting the node modules and run npm i again. and also if that doesnt work check in incognito to make sure its not a cache thing

**Comment by stavares843** [comment]
https://github.com/user-attachments/assets/94d9d15b-6665-48ca-a681-fe0f92379524

i tried that but then the same issue happens

**Comment by stavares843** [comment]
thats a good idea thank you @phillsatellite 🎉

**Review by InfamousVague — APPROVED** [review]

**Pull request merged**
