### PR TITLE
feat(chat): Impl emoji button in reaction

### LINKED ISSUE #482: bug(chats): emoji reaction plus button on context menu of chat message does nothing
1. Create accounts
2. Make them friends
3. Send a message from account one to account two
4. Open context menu on chat message sent
5. On context menu top right there is a "plus" button that should open the emoji picker to select more reactions for the chat message

Expected: Emoji picker should be displayed after clicking on emoji reaction plus button from context menu
Actual: Nothing happens after clicking on emoji reaction plus button from context menu

Note: Happens on both message sent/received context menus

image

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

- Implements the functionality of the plus button in reactions

### Which issue(s) this PR fixes 🔨

- Resolve #482

### CODE REVIEW

**Comment by InfamousVague** [comment]
Does this allow us to choose an emoji from the picker to react with?

**Comment by Flemmli97** [comment]
it opens the picker if you click on the plus

**Review by InfamousVague — APPROVED** [review]

**Comment by InfamousVague** [comment]
> it opens the picker if you click on the plus

We should try to implement the rest of the functionality in a future PR. The idea is that your most frequently used emoji's (this should already be stored in the emoji picker) will be the emoji's that show up as reaction options. Clicking the emoji picker button and then selecting an emoji should automatically apply the emoji as a reaction as opposed to placing the emoji in the chatbar.

I am cool to merge this for now if you want but I can also try to help get this full functionality working together.

**Comment by Flemmli97** [comment]
updated:
picker will auto react to message if used from the message context.
also
added emoji counter that makes most common used emoji appear in message context menu

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
