### PR TITLE
fix(Keyboard): Fix keyboard on mobile

### LINKED ISSUE #915: bug(Mobile): Screen is not responsive when keyboard is opened
- Screen is not responsive when keyboard is opened
- Keyboard open above screen, and hide input elements.

**STR:**
-Go to chat 
-Tap on chatbar
-Keyboard overlaps 

**Screen recording:**

https://github.com/user-attachments/assets/24c669e0-f3d3-4154-b600-c6f20159f724

### LINKED ISSUE #917: bug(iOS): Keyboard remains open when opening sidebar
**Issue:**
When the user is typing in chat, if they open the sidebar the keyboard will remain open 

**STR:**
-Type in chat with the keyboard open 
-Swipe right to open the sidebar 
-Keyboard remains open 

**Screen recording:**

https://github.com/user-attachments/assets/365bcd1a-bd88-4bc4-b0c3-e1cb6bbeeb89

### PR DESCRIPTION
**Pull request by lgmarchi**
### What this PR does 📖

- Fix keyboard on chats for iOS, chatbar is going up when keyboard is opened **(iOS only)**
- Fix bottomNavBar appearing when keyboard is opened, now if keyboard is opened, bottomNavBar will be hided **(iOS and Android)**
- Fix screen on create account and profile for iOS when open keyboard to not hide inputs **(iOS only)**

> [!NOTE]
> Maybe there is a little glitch when you go to chats from friends page, margin between chatbar and keyboard is big, but it just happened first time, if closes keyboard and open again, margin is correct. 

### Which issue(s) this PR fixes 🔨

-   Resolve #915 
- Resolve #917

### CODE REVIEW

**Comment by phillsatellite** [comment]
Hey Lucas I noticed a few issues while testing. 

 **Issues:**
- Switching to a new chat in the sidebar keyboard will overlap the chatbar 

- Going to Friends then tapping chat, keyboard will overlap the chatbar 

https://github.com/user-attachments/assets/fa6f3ca7-627d-41d9-98b7-dc8211939ff7

Also I am thinking we should probably have the keyboard stay open after a user sends a message. That way they dont have to keep re-opening it 

https://github.com/user-attachments/assets/dd60af1e-6d9e-434c-98ab-63d85ae531d9

**Comment by lgmarchi** [comment]
> Hey Lucas I noticed a few issues while testing.
> 
> **Issues:**
> 
> * Switching to a new chat in the sidebar keyboard will overlap the chatbar
> * Going to Friends then tapping chat, keyboard will overlap the chatbar
> 
>  Screen.Recording.2024-12-09.at.5.53.37.PM.mov 
> Also I am thinking we should probably have the keyboard stay open after a user sends a message. That way they dont have to keep re-opening it
> 
>  Screen.Recording.2024-12-09.at.5.55.22.PM.mov

Good points, I will take a look.

**Comment by lgmarchi** [comment]
Now, when we enter in chats, it will build without keyboard
If user click on input, keyboard will be opened
And after send message, keyboard will keep opened

**Comment by phillsatellite** [comment]
Sent Lucas a DM, it looks like everything is fixed except for when the user switches to another chat via the sidebar on both iOS & Android. Other than that last issue all is good!

https://github.com/user-attachments/assets/ea231ec0-4daa-4714-bc9e-fa962943416e

**Review by phillsatellite — APPROVED** [review]

**Review by ashneverdawn — APPROVED** [review]

**Review by stavares843 — APPROVED** [review]

**Pull request merged**
