### PR TITLE
fix(chat): fix group chat perms and modification

### LINKED ISSUE #772: Group settings - Description cannot be changed
Users cannot update the group description in the group settings.

### LINKED ISSUE #774: Group settings - Not creator cannot rename or update group when allow anyone is enabled
When 'allow anyone' is enabled, non-creators still cannot rename or update the group.

### PR DESCRIPTION
**Pull request by Flemmli97**
### What this PR does 📖

~~Fixes some perm issue with group chat:~~
  ~~Fix setting allowAnyoneCanRename not being applied. now it should work for renaming of chat name and description~~
~~Fix setting adding users permission. Now if the permission is false the  participants view list will reflect that~~

- Redo the whole group settings ui:
  - Adding/Removing group members is now done in settings menu
  - "View member" menu now only SHOWS the member and does not allow modifying
  - Settings menu also allows setting the permissions for individual users. Select users by clicking on them
  - Add users to group by clicking on invite button
  - Remove users by selecting and kicking them
  - Removed member list button in topbar chat. Clicking on the group pic already opens the member list (if we want it still we can bring it back)
 
### Which issue(s) this PR fixes 🔨

- Resolve #774
- Resolve #772
- Resolver #662 662

### CODE REVIEW

**Comment by phillsatellite** [comment]
So renaming works good but users still arent able to change the group description 

https://github.com/user-attachments/assets/330db467-db26-4441-a674-3dd0d34a6c0b

**Comment by Flemmli97** [comment]
> So renaming works good but users still arent able to change the group description
> 
>  Screen.Recording.2024-10-29.at.5.51.36.PM.mov

i just looked into it and group description is not a thing in warp. only name. so that whole functionality cant work. should we just go ahead and remove that for now?

**Comment by Flemmli97** [comment]
note requires a pending wasm update

**Review by lgmarchi — APPROVED** [review]
Code looks good to me. But it fails to create new groups. 

Log: 
image

**Review by lgmarchi — CHANGES_REQUESTED** [review]
Not possible to create groups.

**Comment by stavares843** [comment]
@lgmarchi create groups works fine


https://github.com/user-attachments/assets/2fd5f63e-f4a0-42be-bdb7-ebfe6507fd73


are you using the latest on the branch?

do you have wasm 1.5.1? for that you can run `npm run list` to check the version

**Comment by lgmarchi** [comment]
@Flemmli97 I was not possible to rename group name with userB and userC.

https://github.com/user-attachments/assets/11fc4230-b7bc-4264-946a-8cfba2a8e112

Log: 

image

**Review by lgmarchi — CHANGES_REQUESTED** [review]
Not possible to rename group name with other users.

**Comment by phillsatellite** [comment]
Hey Kevin! So Sara and I tested and there were a few issues we found:

*Note that we did verify this is on warp-wasm1.5.1
image

We tried groups of 3+ and group of 2. We also tried an older account (Only a few hours old) and a brand new account

- The group creator is the only one who is able to change the group name. We found that the number of people in the group doesn't matter but anyone who is not the creator cannot change name 

https://github.com/user-attachments/assets/c801f1dc-c2a5-4871-b238-957f199b8030

Screenshot 2024-11-05 at 7 21 04 PM

- The permission settings are not updated, if group creator disables the ability for other users to change names , then goes to settings and back to the group chat again, the ability to for others to change name will still be enabled 

https://github.com/user-attachments/assets/14bc78a2-a04e-45af-a257-8d1178210fca

This error happens when the user hits save
image

- No save button appears when you try to edit the group description 
image

**Comment by Flemmli97** [comment]
permission system got redone with new wasm update.

**Comment by phillsatellite** [comment]
> permission system got redone with new wasm update.

Yeah wasn't this supposed to work with the new wasm update? Thats why this pr was waiting on the wasm pr correct?

**Comment by stavares843** [comment]
added blocked label, being discussed with flem

**Comment by stavares843** [comment]
after discussing with flem, the above will be addressed on the PR

**Comment by phillsatellite** [comment]
@Flemmli97 Hey Kevin, so Sara and I have be retesting and some of the stuff is fixed but theres 2 that still aren't working

- User who is not group creator cannot remove/kick people. When they try to the option for the user just remains. They are able to add users perfectly fine though

https://github.com/user-attachments/assets/2f592112-46a0-4f56-8c27-d1ece169cb8b

- Both group creator and members are not able to save the description

https://github.com/user-attachments/assets/5bbf2bf6-f19f-4a28-bedc-850165b8bee5

**Review by phillsatellite — APPROVED** [review]

**Comment by phillsatellite** [comment]
This needs another update from Warp to get description and kicking working properly. Kevin will be addressing these in another pr

**Review by InfamousVague — APPROVED** [review]

**Review by lgmarchi — APPROVED** [review]

**Pull request merged**
